//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldarAliev.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONSUMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONSUMER()
        {
            this.REQUEST = new HashSet<REQUEST>();
        }
    
        public int Code { get; set; }
        public string Title { get; set; }
        public string Address { get; set; }
        public string Invoice { get; set; }
        public string INN { get; set; }
        public int CodeProfile { get; set; }
    
        public virtual PROFILE PROFILE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REQUEST> REQUEST { get; set; }
    }
}
