//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EldarAliev.BD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entrance
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public string Attempts { get; set; }
        public string LoginSuccess { get; set; }
        public int SignlnID { get; set; }
        public string Login { get; set; }
    
        public virtual SignIn SignIn { get; set; }
    }
}
